### ISSUE TITLE
Hack simple query scenario to get upper bound for TDS/SQL Server

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/datalab#12]
The idea here is to take the simple scenario implemented in #11 and hack together a raw implementation using low-level .NET constructors to hard-code some TDS. This gives us an upper bound as to how much perf is potentially on the table, at least in the very simple case.

**Comment by roji** [comment]
Closing issues as part of the repo archiving, see #22 for a summary of Woodstar.
