### ISSUE TITLE
Folder Structure

### ISSUE THREAD

**Issue by Drawaes** [dotnet/datalab#14]
What should the folder structure look like for some rough starting place code? I am pretty busy but am hoping to carve out a little time to write a basic "connect, do a query, get a result" code but would like to avoid having to rename and refolder everything after I have made it.

I am proposing folder under the "datalab" folder of

datalab/SqlServer.Core

and then  a solution file in that folder with the same name and then two sub folders under that

/src
/test

for now that is all I would really need, with "projects" under the src mostly

**Comment by Drawaes** [comment]
Just as a note, I don't really care, I just don't want to spend a PR redoing it all, so if you have a different preferred structure I am okay with it.

**Comment by roji** [comment]
@Drawaes sorry for the late reply.

Since the repro is already called datalab, I'm not sure we need an additional directory with that name - I'd just place SqlServer.Core at the root. Apart from that what you suggest seems good - and of course we can always move things around later if we want.

**Comment by roji** [comment]
Closing issues as part of the repo archiving, see #22 for a summary of Woodstar.
