### ISSUE TITLE
guidance on an Apache Arrow Layer

### ISSUE THREAD

**Issue by caljnj** [dotnet/datalab#17]
Hi

I'm working off a [comment by yzorg](https://github.com/dotnet/datalab/issues/6#issuecomment-847237909) regarding integration of Apache Arrow into this project, and the answer was that this would be implemented at a higher layer than driver level. 

I was after some pointers really,. my aim here is to intercept the ODBC driver's storage mechanism, and store it to "feather" format instead (a SIMd memory-optimized file format).

can you recommend:

- materials to skill up on the current ODBC driver
- a good place to try to insert what i'm doing in the current ODBC driver
- other example projects that do a similar thing..?

Thanks!

**Comment by roji** [comment]
@caljnj modern approaches to database drivers in .NET typically don't include ODBC - high-performance drivers and experiments are currently fully managed, 100% .NET implementations.

Some more context on what you're planning to achieve would be useful; are you looking to create some sort of database driver over Apache Arrow, or something that bridges/integrates a relational database (e.g. SQL Server) with Apache Arrow? If it's the former, a .NET Apache Arrow library seems to [already exist](https://github.com/apache/arrow/blob/master/csharp/README.md).

**Comment by caljnj** [comment]
sorry! misunderstood what you were all up to here. 
what i was after i guess was to do the layer above the driver. 
Excactly like turbodbc does for Python. but with bindings for the R language.
https://arrow.apache.org/blog/2017/06/16/turbodbc-arrow/
