### ISSUE TITLE
Another Tds client

### ISSUE THREAD

**Issue by Anderman** [dotnet/datalab#18]
4 years ago I did a almost complete rewrite of the sqlClient for fun and to do some performance test. The bulk insert was fast but for small queries the improvement was small. Most of the time was spend on the sql server and communication.
Async was wrong implemented and probably much more but a lot could be simplified. 

the Repo can be found [here](https://github.com/Anderman/TdsClient). 

The old repro was based on a data reader and writer. I skipped that part and did the reading and writing directly to a poco. I think with EF core this should also possible. There is some mapping between sql fields and poco properties and there are some value convertors.

Directly converting json strings from the input stream will skip the copy part.

**Comment by roji** [comment]
Closing issues as part of the repo archiving, see #22 for a summary of Woodstar.
