### ISSUE TITLE
Progress?

### ISSUE THREAD

**Issue by Wraith2** [dotnet/datalab#19]
It was mentioned on an EF livestream that progress was being made but the only commit is from 2021. Is there code being worked on? If so can we see it in case we can help out?

**Comment by roji** [comment]
@Wraith2 there's definitely been progress, and we're also discussing internally about future directions for this. We'll communicate on this soon, hang tight.

**Comment by Wraith2** [comment]
How soon?

**Comment by roji** [comment]
We'll very likely post an update in the next few weeks.

**Comment by ilmax** [comment]
Just out of curiosity, why is this being worked on behind closed doors at the moment?

**Comment by LeftTwixWand** [comment]
From what I see: Woodstar been added as one of the goals of EF Core 8:
https://github.com/dotnet/efcore/issues/29853

**Comment by ymotton** [comment]
> Just out of curiosity, why is this being worked on behind closed doors at the moment?

Bump ^

Would love to see this opened up to the community.
If we've learned anything from the last couple of years, performance work gets a lot of outside eyeballs and contributions.
Please, let us help.

**Comment by Wraith2** [comment]
> We'll communicate on this soon, hang tight.

It's 4 months later. Can you define "soon" for me?

**Comment by ilmax** [comment]
> We'll very likely post an update in the next few weeks.

Also few now has a whole different meaning to me 😄

**Comment by roji** [comment]
Everyone, we're now heads-down in the last phases of .NET/EF 8.0 feature work, before the window for improvements closes. I hoped to be able to do this much earlier, but unfortunately there have been many unscheduled things that required our attention.

We'll post an update once the release goes into stabilization and things calm down a bit.

**Comment by Tornhoof** [comment]
@roji as rc1 ist out now, what about a tiny update?

**Comment by Wraith2** [comment]
Given that EF 8 is now in stabilization mode, per https://github.com/dotnet/efcore/issues/29853#issuecomment-1703932526 can we get some information what's going on please? Even if we don't get code can we get some sort of information about what's happened and what is yet to happen?

**Comment by roji** [comment]
@Wraith2 unfortunately I'm still extremely busy with 8.0-related work, and that's unlikely to change before the release in November. We've done some investigation and prototype coding in 8.0, but a serious write-up is needed to describe that, and I simply don't have the time to do that at the moment.

I'm sorry things are taking this long, but it is what it is. I promise that once I get some breathing space I'll prioritize summarizing what we've done and the state of affairs.

**Comment by PureKrome** [comment]
Keep up the awesome work @roji (and team). We respect what you're doing 🤗

**Comment by Varorbc** [comment]
@roji any update ?

**Comment by roji** [comment]
Not yet.

**Comment by jernejk** [comment]
@roji, apologies for the probe but is the adapter going to be ready by February?

I'm doing a talk about EF Core + SQL Server; a deeper dive and at least having information on differences would be greatly appreciated. Especially, if the "async" issue will be fixed when needing to download multiple MBs from SQL Server to .NET.

The plan is to show less-known features of EF Core and SQL Server, as well as how to make them work well together, as there is very little material on this.

**Comment by Wraith2** [comment]
> specially, if the "async" issue will be fixed when needing to download multiple MBs from SQL Server to .NET.

You may want to know about https://github.com/dotnet/SqlClient/pull/2164 which should be in the next full release.

**Comment by jernejk** [comment]
Thank you, @Wraith2! :)

I checked this GB issue weeks ago, and then I tried with the Preview 3 version of the adapter and EF Core 8 RC2.
My demo currently uses Microsoft.Data.SqlClient 5.2.0-preview3.23201.1 and EF Core 8.0.0 but I'll return to this once preview 4 is out. :) (or try to set it up locally if I get too bored on Xmas)

I still would appreciate it if there are any more in-depth differences between SqlServer.Core and Microsoft.Data.SqlClient that I could mention at my talk to get people excited for its release. :)

**Comment by mburbea** [comment]
It's been a few months since the last poke, but any updates @roji?

**Comment by Wraith2** [comment]
anything?

**Comment by vonzshik** [comment]
> anything?

Something's going on with SqlClient (https://github.com/dotnet/SqlClient/pull/2570) ...

**Comment by edwardneal** [comment]
We're starting to see PRs for SqlClientX merged, so I'd definitely be interested to understand what the roadmap for this is and what design work's already been done.

**Comment by Wraith2** [comment]
There is a discussion about SqlClientX here https://github.com/dotnet/SqlClient/discussions/2603 which I encourage everyone to read through and ask questions in.
There is also an in depth discussion about connection pooling and how the new implementation is going to work here https://github.com/dotnet/SqlClient/discussions/2612

It looks like any innovation is going to happen in SqlClient by having a secondary set of code in the library written by the SqlClient and SqlServer teams rather than being implemented externally in woodstar. This all smells like internal MS politics to me but whatever is going on we'll probably never understand the reasons.

**Comment by ajcvickers** [comment]
@Wraith2 If I have any credit built up with the community over the years, then let me use some to  just say what is happening in SqlClient is **good**. Of course, politics are involved, but fundamentally there is enthusiasm and investment in making SQL connectivity in .NET better. This is **good**! Celebrate! 🥳 🍾 🎆

**Comment by ErikEJ** [comment]
@ajcvickers We owe each other beers! 😄

**Comment by roji** [comment]
Please see #22 for a short summary of the Woodstar experiment.
