### ISSUE TITLE
Communication and collaboration

### ISSUE THREAD

**Issue by ajcvickers** [dotnet/datalab#9]
This issue tracks ways we will communicate and collaborate on [Woodstar (SQL Server.Core)](https://github.com/dotnet/datalab/issues/6). Please let us know what works for you, and also comment with your own ideas.

Some initial ideas:

* Discord/Slack channel or similar
* GitHub discussions on this repo
* Teams/Zoom meetings with some/all collaborators
* Live streaming

@ErikEJ @wraith2 @NickCraver @mgravell @Drawaes

/cc @davidfowl

**Comment by ErikEJ** [comment]
Combination of persisted chat and teams/zoom meetings

**Comment by Wraith2** [comment]
We can get a channel on the [dotnet discord](https://aka.ms/dotnet-discord). 
I'm open to any/all, whatever is most easy for most people.

**Comment by roji** [comment]
Closing issues as part of the repo archiving, see #22 for a summary of Woodstar.
